# Generated by Django 4.1.1 on 2022-09-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainIndex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='dofb',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='psw',
            field=models.CharField(max_length=50),
        ),
    ]
