# Generated by Django 4.1.1 on 2022-09-27 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainIndex', '0002_alter_users_dofb_alter_users_email_alter_users_psw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_published', models.TimeField(auto_created=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300, null=True)),
                ('sold', models.BooleanField(default=False)),
                ('next_owner', models.CharField(max_length=50, null=True)),
                ('ads_removed', models.TimeField(null=True)),
                ('nickname', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='MainIndex.users')),
            ],
        ),
    ]
