# Generated by Django 4.0.6 on 2022-10-11 09:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MainIndex', '0010_alter_users_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='ads_published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 11, 9, 47, 1, 111677, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='ads_removed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='next_owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='sold',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 11, 9, 47, 1, 51677, tzinfo=utc), null=True),
        ),
    ]
