# Generated by Django 4.0.6 on 2022-10-12 08:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MainIndex', '0011_alter_catalogue_ads_published_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogue',
            old_name='nickname',
            new_name='publisher',
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='ads_published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 12, 8, 38, 39, 694033, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='sold',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 12, 8, 38, 39, 658034, tzinfo=utc), null=True),
        ),
    ]
