# Generated by Django 4.0.6 on 2022-10-12 08:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MainIndex', '0012_rename_nickname_catalogue_publisher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='publisher_nn',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='ads_published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 12, 8, 47, 36, 209195, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 12, 8, 47, 36, 169195, tzinfo=utc), null=True),
        ),
    ]
