# Generated by Django 4.0.6 on 2022-10-17 17:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MainIndex', '0013_catalogue_publisher_nn_alter_catalogue_ads_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='geo_position',
            field=models.CharField(default='Unspecified', max_length=50),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='item_tags',
            field=models.CharField(default='Unspecified', max_length=300),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='ads_published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 17, 17, 46, 0, 843331, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 17, 17, 46, 0, 809332, tzinfo=utc), null=True),
        ),
    ]
