# Generated by Django 4.0.6 on 2022-10-19 15:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MainIndex', '0016_catalogue_number_of_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='ads_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 19, 15, 46, 51, 556652, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='img',
            field=models.ImageField(default='logos/trashbin.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 19, 15, 46, 51, 516658, tzinfo=utc)),
        ),
    ]
