# Generated by Django 4.0.6 on 2022-10-19 15:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MainIndex', '0017_alter_catalogue_ads_published_alter_catalogue_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='ads_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 19, 15, 51, 51, 883018, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='img',
            field=models.ImageField(default='logos/trashbin.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 19, 15, 51, 51, 843017, tzinfo=utc)),
        ),
    ]
