# Generated by Django 4.0.6 on 2022-10-20 16:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MainIndex', '0019_alter_catalogue_ads_published_alter_catalogue_img_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogue',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='catalogue',
            name='city',
            field=models.CharField(default='///', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogue',
            name='region',
            field=models.CharField(default='//', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogue',
            name='state',
            field=models.CharField(default='/', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='bio',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='wishlist',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='ads_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 20, 16, 35, 31, 913839, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='geo_position',
            field=models.CharField(default='<django.db.models.fields.CharField>, <django.db.models.fields.CharField>, <django.db.models.fields.CharField>', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 20, 16, 35, 31, 881840, tzinfo=utc)),
        ),
    ]
