# Generated by Django 4.0.6 on 2022-10-27 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainIndex', '0024_users_django_model_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogue',
            old_name='state',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='ads_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 2, 34, 2, 317511)),
        ),
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 2, 34, 2, 316511)),
        ),
    ]
