# Generated by Django 4.0.6 on 2022-11-04 10:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainIndex', '0025_rename_state_catalogue_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='users',
            name='item1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MainIndex.catalogue'),
        ),
        migrations.AddField(
            model_name='users',
            name='item2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MainIndex.catalogue'),
        ),
        migrations.AddField(
            model_name='users',
            name='item3',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MainIndex.catalogue'),
        ),
        migrations.AddField(
            model_name='users',
            name='item4',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MainIndex.catalogue'),
        ),
        migrations.AddField(
            model_name='users',
            name='item5',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MainIndex.catalogue'),
        ),
        migrations.AddField(
            model_name='users',
            name='wishlist_items',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='ads_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 11, 10, 48, 294306)),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 11, 10, 48, 294306)),
        ),
    ]
