# Generated by Django 4.0.6 on 2022-11-07 16:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainIndex', '0027_alter_catalogue_ads_published_alter_users_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='ads_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 17, 16, 40, 526400)),
        ),
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 17, 16, 40, 527400)),
        ),
        migrations.AlterField(
            model_name='users',
            name='item1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MainIndex.catalogue'),
        ),
        migrations.AlterField(
            model_name='users',
            name='item2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MainIndex.catalogue'),
        ),
        migrations.AlterField(
            model_name='users',
            name='item3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MainIndex.catalogue'),
        ),
        migrations.AlterField(
            model_name='users',
            name='item4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MainIndex.catalogue'),
        ),
        migrations.AlterField(
            model_name='users',
            name='item5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MainIndex.catalogue'),
        ),
    ]
