# Generated by Django 4.0.6 on 2022-11-07 20:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainIndex', '0028_alter_catalogue_ads_published_alter_users_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='item1',
        ),
        migrations.RemoveField(
            model_name='users',
            name='item2',
        ),
        migrations.RemoveField(
            model_name='users',
            name='item3',
        ),
        migrations.RemoveField(
            model_name='users',
            name='item4',
        ),
        migrations.RemoveField(
            model_name='users',
            name='item5',
        ),
        migrations.RemoveField(
            model_name='users',
            name='wishlist_items',
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='ads_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 21, 57, 10, 474950)),
        ),
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 21, 57, 10, 475948)),
        ),
        migrations.CreateModel(
            name='UsersWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchlist_items', models.IntegerField(null=True)),
                ('item1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MainIndex.catalogue')),
                ('item2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MainIndex.catalogue')),
                ('item3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MainIndex.catalogue')),
                ('item4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MainIndex.catalogue')),
                ('item5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MainIndex.catalogue')),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='watchlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MainIndex.userswatchlist'),
        ),
    ]
