# Generated by Django 4.0.6 on 2022-11-07 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainIndex', '0029_remove_users_item1_remove_users_item2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='popularity',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='ads_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 22, 6, 13, 80138)),
        ),
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 22, 6, 13, 81138)),
        ),
        migrations.AlterField(
            model_name='userswatchlist',
            name='watchlist_items',
            field=models.IntegerField(default=0),
        ),
    ]
