# Generated by Django 4.0.6 on 2022-11-08 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainIndex', '0031_alter_catalogue_ads_published_alter_users_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogue',
            name='geo_position',
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='ads_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 8, 16, 22, 48, 571332)),
        ),
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 8, 16, 22, 48, 572334)),
        ),
    ]
