# Generated by Django 4.0.6 on 2022-11-08 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainIndex', '0032_remove_catalogue_geo_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='geo_position',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='ads_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 8, 16, 29, 38, 538111)),
        ),
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 8, 16, 29, 38, 539110)),
        ),
    ]
