# Generated by Django 4.0.6 on 2022-11-10 22:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainIndex', '0033_catalogue_geo_position_alter_catalogue_ads_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userswatchlist',
            name='owner',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userswatchlist',
            name='owner_nn',
            field=models.CharField(default='broski', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='ads_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 10, 23, 0, 5, 588411)),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='publisher_nn',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 10, 23, 0, 5, 589412)),
        ),
    ]
