# Generated by Django 4.0.6 on 2022-11-10 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainIndex', '0034_userswatchlist_owner_userswatchlist_owner_nn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='ads_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 10, 23, 45, 40, 517516)),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='publisher_nn',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 10, 23, 45, 40, 518510)),
        ),
    ]
