# Generated by Django 4.1.1 on 2022-09-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('created', models.TimeField(auto_created=True)),
                ('nickname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('psw', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('dofb', models.DateTimeField(null=True)),
            ],
        ),
    ]
