# Generated by Django 4.0.6 on 2022-10-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainIndex', '0006_alter_catalogue_ads_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='ads_published',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='ads_removed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
