# Generated by Django 4.0.6 on 2022-10-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainIndex', '0007_alter_catalogue_ads_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(default='02-10-22 // 20:05:29', null=True),
        ),
    ]
