# Generated by Django 4.0.6 on 2022-10-02 18:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MainIndex', '0009_alter_users_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 2, 18, 14, 2, 408021, tzinfo=utc), null=True),
        ),
    ]
