# Generated by Django 4.0.6 on 2022-10-18 16:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MainIndex', '0015_rename_sold_catalogue_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='number_of_items',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='ads_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 16, 27, 27, 892821, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='geo_position',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='item_tags',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 16, 27, 27, 851316, tzinfo=utc)),
        ),
    ]
